"use client";
import "../styles/globals.css";
import Header from "../components/Header";
import MainContainer from "../components/MainContainer";
import Footer from "../components/Footer";
import { CouncilProvider } from "./providers";
import SplashScreen from "../components/SplashScreen";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import WelcomePopup from "../components/WelcomePopup";
import DesktopWelcomePopup from "../components/DesktopWelcomePopup";
import { useMediaQuery } from "react-responsive";

// export const metadata = {
//   title: "Binfluence - Recycling is EASY!",
//   description: "Generated by create next app",
// };



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathName = usePathname();
  const isHome = pathName === "/";
  const [isLoading, setIsLoading] = useState<boolean>(isHome);

  useEffect(() => {
    if (isLoading) return;
  }, [isLoading]);

  const isMobile = useMediaQuery({ query: "(max-width: 600px)" });
  const isPc = useMediaQuery({ query: "(min-width: 601px)" });
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="./favicon.ico?v=2" type="image/x-icon" />
      </head>

      <body className="root">
        {isLoading && isHome ? (
          <SplashScreen finishLoading={() => setIsLoading(false)} />
        ) : (
          <CouncilProvider>
            {isMobile && <WelcomePopup />}
            {isPc && <DesktopWelcomePopup />}

            <Header />
            <MainContainer>{children}</MainContainer>
          </CouncilProvider>
        )}
      </body>
    </html>
  );
}